### ISSUE TITLE
Text Analysis Functions

### ISSUE THREAD

**Issue by Stefan4472** [Plain-Simple/TextManipulator#1]
Each will take String text by reference, entered by the user, and return 
public static int WordCount(String text);
public static int CharCount(String text);
public static int LineCount(String text);
public static int SentenceCount(String text);
public static void WordFrequency(String text); // should print a table of word frequencies
public static void CharFrequency(String text); // should print a table of char frequencies

Many of these functions can be found in the C++ version but need refactoring, improvement, or fixing.

**Comment by UnsolvedCypher** [comment]
It looks like the first three functions have been implemented, I will work on the next three after the CLI is in better shape.

**Comment by Stefan4472** [comment]
Finished frequency functions, although they need to be tested and perhaps made more efficient.
