### ISSUE TITLE
Make the GUI More Attractive

### ISSUE THREAD

**Issue by Stefan4472** [Plain-Simple/TextManipulator#10]
-I'm thinking of a red and white scheme. White background, red button outlines, red textarea outline, etc. Eventually we will create a custom theme.
-In the bottom right we can have "Plain+Simple Programming"

**Comment by UnsolvedCypher** [comment]
I think this can be closed for now until we are very good at Java. Currently, the system theme should suffice. Stefan, please close this if you agree.

**Comment by Stefan4472** [comment]
Oh I just meant some simple aesthetic features, nothing too complex. But
I'll close it for now and can always reopen it later.
