### ISSUE TITLE
Structural improvements in ManipulateText

### ISSUE THREAD

**Issue by UnsolvedCypher** [Plain-Simple/TextManipulator#39]
Instead of having each function return a string, it may be more efficient to make text a public variable and have each function modify that. Thoughts @derikk @Stefan4472 ?

**Comment by Stefan4472** [comment]
Personally I think it would be better practice to have each function able
to run independently and to avoid hardcoding. Also, doing that would make
it incompatible with the CLI.

**Comment by UnsolvedCypher** [comment]
Now that I'm farther into the CLI, that was a really bad idea. You are completely right, it should be left as-is.
