### ISSUE TITLE
Organize i18n Strings

### ISSUE THREAD

**Issue by Stefan4472** [Plain-Simple/TextManipulator#45]
Organize in whatever way you feel is easiest to use and makes sense.

**Comment by UnsolvedCypher** [comment]
As of now, I will stick with one file and organize using comments within the file, but we may switch to using multiple files in the future if it makes sense.

**Comment by UnsolvedCypher** [comment]
We're no longer using resource bundles and Messages.java should contain all strings needed. I don't think further organization is needed at this time.
