### ISSUE TITLE
Implement More Regex (ManipulateText)

### ISSUE THREAD

**Issue by Stefan4472** [Plain-Simple/TextManipulator#47]
Many functions in ManipulateText are currently using hand-written code that could be greatly simplified and improved by using regex and the String.split() methods.

**Comment by UnsolvedCypher** [comment]
If you see code like this in the future, could you add a //TODO: comment so that it's easier to find?

**Comment by Stefan4472** [comment]
I've done a good amount of refactoring to implement more regex, I think this can be closed. Though obviously we will still be trying to implement regex when possible, as it has superior algorithms than what we can write.
