### ISSUE TITLE
Improve CLI Command Syntax

### ISSUE THREAD

**Issue by Stefan4472** [Plain-Simple/TextManipulator#49]
Input should be in the format of: tm [function_name] [parameter1] [parameter2] ... -flag [flagparameter (if necessary)]...

**Comment by UnsolvedCypher** [comment]
I think the function name should be a flag.

**Comment by Stefan4472** [comment]
This is now obsolete as we will be shifting over to the Apache Commons CLI Library. Matt, please close the issue if you agree.

**Comment by UnsolvedCypher** [comment]
Agreed. I'll open a new comment for the implementation of Apache CLI.
